// Copyright (c) 2021-2024 AXE, Inc.
// SPDX-License-Identifier: GPL-3.0-or-later

`define ROS2_MAX_NODE_NAME_LEN        32
`define ROS2_MAX_TOPIC_NAME_LEN       32
`define ROS2_MAX_TOPIC_TYPE_NAME_LEN  64
`define ROS2_MAX_APP_DATA_LEN         1024
`define ROS2_APP_DATA_LEN_WIDTH       ($clog2(`ROS2_MAX_APP_DATA_LEN+1))

// `define ROS2_PUB_DATA_FF
`define ROS2_PUB_DATA_RAM

// `define ROS2_SEDP_READER_TBL_FF
`define ROS2_SEDP_READER_TBL_RAM

`define ROS2_PUB_TOPICS_MAX 4
`define ROS2_SUB_TOPICS_MAX 4

`ifdef ROS2RAPPER_HLS_VITIS
  `define ROS2_RTPS_DATA_WIDTH        216
  `define ROS2_MESSAGE_METADATA_WIDTH 384
`elsif ROS2RAPPER_HLS_CWB
  `define ROS2_RTPS_DATA_WIDTH        211
  `define ROS2_MESSAGE_METADATA_WIDTH 374
`endif

`define ROS2_SEDP_READER_MAX 1024
`define ROS2_APP_READER_MAX  128
`define ROS2_SEDP_ENDPOINT_WIDTH (565 + `ROS2_APP_READER_MAX)

`define PAYLOADSMEM_DEPTH   2960
`define PAYLOADSMEM_AWIDTH  ($clog2(`PAYLOADSMEM_DEPTH))

`define UDP_RXBUF_AWIDTH 6
`define UDP_TXBUF_AWIDTH 6
