# Copyright (c) 2021-2026 AXE, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

HLSDIR = hls
#SRCS = $(wildcard $(HLSDIR)/*.cpp)
SRCS_MAIN = hls/endpoint.cpp hls/message_metadata.cpp hls/remove_endpoints.cpp hls/ros2.cpp hls/spdp.cpp
SRCS_RECEIVER = hls/app.cpp hls/checksum.cpp hls/ip.cpp hls/remove_endpoints.cpp hls/ros2_receiver.cpp hls/rtps.cpp hls/sedp.cpp hls/slip.cpp hls/spdp.cpp hls/udp.cpp
SRCS_SENDER = hls/app.cpp hls/ip.cpp hls/message_metadata.cpp hls/ros2_sender.cpp hls/sedp.cpp hls/slip.cpp hls/spdp.cpp hls/udp.cpp
HDRS = $(wildcard $(HLSDIR)/*.hpp)

.PHONY: synth clean format

CPARS_FLAGS =
BDLTRAN_FLAGS = -c10000 -s -Zresource_fcnt=GENERATE -Zresource_mcnt=GENERATE -Zport_optimize -Fc:clk+ -Fr:rst_n- -Zdup_reset=YES -Zreg_min_reset=NO -Zreset_enable_reg=YES -apI:o -Zmem_kind=RW1 -mrewe -Zmem_stall=data_hold_reg -Zmem_cs -Zshared_mem_re_gen=NO -Zfolding_sharing=inter_stage -OW-B -Wattr=error -lb ${CYBER_PATH}/packages/asic_90.BLIB -lfl ${CYBER_PATH}/packages/asic_90.FLIB -TC172 -o-P
VGEN_FLAGS = -mem_black_box=YES -case_default_x=NO

synth: ros2_main_cwb.v ros2_receiver_cwb.v ros2_sender_cwb.v

ros2_main.IFF: $(SRCS_MAIN) $(HDRS)
	cpars $(CPARS_FLAGS) $(SRCS_MAIN)

ros2_receiver.IFF: $(SRCS_RECEIVER) $(HDRS)
	cpars $(CPARS_FLAGS) $(SRCS_RECEIVER)

ros2_sender.IFF: $(SRCS_SENDER) $(HDRS)
	cpars $(CPARS_FLAGS) $(SRCS_SENDER)

%_E.IFF: %.IFF
	bdltran $(BDLTRAN_FLAGS) $<

%_cwb.v: %_E.IFF
	veriloggen $(VGEN_FLAGS) -o $@ $<

clean:
	rm -f *.CPINFO *.cperr *.xml *.FCNT *.FLIB *.MCNT *.MLIB *.CSV *.LMSPEC *.LOG.gz *.QOR *.QOR.HTML *.SR *.SUMM *.VSG *.err *.tips *.v *.LSInfo *.scuba *.vgerr *.warn *.IFF *.json

format:
	-clang-format -i hls/*.cpp
	-clang-format -i hls/*.hpp
	-clang-format -i test/*.cpp
	-clang-format -i test/*.hpp
